# Generated by Django 2.1.7 on 2019-02-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('depart_num', models.IntegerField(primary_key=True, serialize=False)),
                ('depart_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=20, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='meetingroom',
            fields=[
                ('room_num', models.IntegerField(primary_key=True, serialize=False)),
                ('room_location', models.CharField(max_length=20, null='False')),
                ('room_size', models.IntegerField(null='False')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('sno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=8, null='False')),
                ('user_name', models.CharField(max_length=20)),
                ('depart_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='room_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.meetingroom'),
        ),
    ]
