# Generated by Django 2.1.7 on 2019-02-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190223_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='depart_name',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='meeting',
            name='sname',
            field=models.CharField(max_length=8, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='meeting',
            name='theme',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='department',
            name='depart_name',
            field=models.CharField(max_length=20, null='False'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn', to='app.meetingroom'),
        ),
    ]
