# Generated by Django 2.1.7 on 2019-02-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190223_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='room_num',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rn', to='app.meetingroom'),
        ),
    ]
