# Generated by Django 2.1.7 on 2019-02-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_meeting_room_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='test',
            field=models.CharField(max_length=10, null='TRUE'),
            preserve_default='TRUE',
        ),
    ]
