# Generated by Django 2.1.7 on 2019-02-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_meeting_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='room_num',
            field=models.IntegerField(null='False'),
            preserve_default='False',
        ),
    ]
