# Generated by Django 2.1.7 on 2019-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_meeting_room_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participate_num',
            field=models.IntegerField(null='False'),
            preserve_default='False',
        ),
    ]
