# Generated by Django 2.1.7 on 2019-02-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_meeting_participate_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='test',
        ),
    ]
