# Generated by Django 2.1.7 on 2019-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_meeting_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='face_id',
            field=models.CharField(max_length=20, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='staff',
            name='user_code',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
    ]
