# Generated by Django 2.1.7 on 2019-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190227_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date',
            field=models.DateField(null='False'),
            preserve_default='False',
        ),
    ]
