# Generated by Django 2.1.7 on 2019-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_staff_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='end_time',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='staff',
            name='start_time',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
    ]
