# Generated by Django 2.1.7 on 2019-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190227_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
