# Generated by Django 2.1.7 on 2019-02-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190227_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sname',
            field=models.CharField(max_length=8, null='True'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_code',
            field=models.CharField(max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_name',
            field=models.CharField(max_length=20, null='True'),
        ),
    ]
