# Generated by Django 2.1.7 on 2019-02-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190227_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='start_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='staff',
            name='depart_num',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
