# Generated by Django 2.1.7 on 2019-02-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190228_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='sname',
            field=models.CharField(max_length=20, null='False'),
        ),
    ]
