# Generated by Django 2.1.7 on 2019-02-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190228_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='sname',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user_code',
        ),
        migrations.AddField(
            model_name='staff',
            name='user_num',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
