# Generated by Django 2.1.7 on 2019-02-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190228_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='depart_name',
        ),
    ]
