# Generated by Django 2.1.7 on 2019-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_meeting_depart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cancel_state',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='department',
            name='edit_state',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
    ]
