# Generated by Django 2.1.7 on 2019-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190304_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
    ]
