# Generated by Django 2.1.7 on 2019-03-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_staff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone_num',
            field=models.IntegerField(null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='staff',
            name='wx_num',
            field=models.IntegerField(null='False'),
            preserve_default='False',
        ),
    ]
