# Generated by Django 2.1.7 on 2019-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190304_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='face_id',
            field=models.ImageField(default='s', max_length=20, null=True, upload_to=''),
        ),
    ]
