# Generated by Django 2.1.7 on 2019-03-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190304_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='cancel_state',
            field=models.CharField(default='false', max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='staff',
            name='edit_state',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_num',
            field=models.IntegerField(null=True),
        ),
    ]
