# Generated by Django 2.1.7 on 2019-03-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190304_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='Participants',
            field=models.CharField(max_length=1000, null='False'),
            preserve_default='False',
        ),
    ]
