# Generated by Django 2.1.7 on 2019-03-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_meeting_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='Participants',
            new_name='participant',
        ),
    ]
