# Generated by Django 2.1.7 on 2019-03-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190307_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_name',
            new_name='create_name',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participate_num',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='sname',
        ),
    ]
