# Generated by Django 2.1.7 on 2019-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190308_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(max_length=20, null='False'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.CharField(max_length=20, null='False'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.CharField(max_length=20, null='False'),
        ),
    ]
