# Generated by Django 2.1.7 on 2019-03-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_meeting_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(max_length=20, null='False'),
        ),
    ]
