# Generated by Django 2.1.7 on 2019-03-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_meeting_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.CharField(max_length=20, null='False'),
        ),
    ]
