# Generated by Django 2.1.7 on 2019-03-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190309_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='create_num',
            field=models.IntegerField(null='False'),
            preserve_default='False',
        ),
    ]
