# Generated by Django 2.1.7 on 2019-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20190310_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='equipment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
