# Generated by Django 2.1.7 on 2019-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_meetingroom_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='cancel_state',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='edit_state',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
    ]
