# Generated by Django 2.1.7 on 2019-03-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20190311_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='room_size',
            field=models.CharField(max_length=20, null='False'),
        ),
    ]
