# Generated by Django 2.1.7 on 2019-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20190312_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='username',
            field=models.TextField(),
        ),
    ]
