# Generated by Django 2.1.7 on 2019-03-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20190312_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cancel_state',
            field=models.CharField(default='false', max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='meeting',
            name='edit_state',
            field=models.CharField(max_length=20, null='False'),
            preserve_default='False',
        ),
    ]
