# Generated by Django 2.1.7 on 2019-03-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20190318_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='condition',
            field=models.CharField(max_length=20, null='modify'),
            preserve_default='modify',
        ),
    ]
