# Generated by Django 2.1.7 on 2019-03-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20190319_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='room_num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
