# Generated by Django 2.1.7 on 2019-03-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20190324_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='room_num',
            field=models.CharField(max_length=20, null='False'),
        ),
    ]
